[package]
name = "Multi-env"
edition = "2021"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
dotenv = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
config = "0.14"
serde_yaml = "0.9"